mugoweb_ibexa_query:
  path: /query
  defaults:
    _controller: 'MugoWeb\IbexaBundle\Controller\QueryController::query'

mugoweb_ibexa_find_location:
  path: /location/{locationId}
  defaults:
    _controller: 'MugoWeb\IbexaBundle\Controller\QueryController::location'

mugoweb_ibexa_regenerate_url_alias:
  path: /url_alias/regenerate
  defaults:
    _controller: 'MugoWeb\IbexaBundle\Controller\ToolsController::regenerateUrlAlias'

mugo_inspect:
  path: /inspect/{type}/{id1}/{id2}
  defaults:
    _controller: MugoWeb\IbexaBundle\Controller\InspectController::inspect
    type: ''
    id1: 0
    id2: 0
