services:
  # Commands
  MugoWeb\IbexaBundle\Command\PurgeTrashCommand:
    arguments:
      - '@ezpublish.api.repository'
    tags:
    - { name: console.command }

  MugoWeb\IbexaBundle\Command\DumpUserHashVariations:
    arguments:
      $cachePool: '@ezpublish.cache_pool'
    tags:
      - { name: console.command }

  MugoWeb\IbexaBundle\Controller\QueryController:
    autowire: true
    autoconfigure: true

  MugoWeb\IbexaBundle\Controller\ToolsController:
    autowire: true
    autoconfigure: true
