services:
  # Commands
  MugoWeb\IbexaBundle\Command\PurgeTrashCommand:
    arguments:
      - '@ezpublish.api.repository'
    tags:
    - { name: console.command }

  MugoWeb\IbexaBundle\Command\DumpUserHashVariations:
    arguments:
      $cachePool: '@ezpublish.cache_pool'
    tags:
      - { name: console.command }

  MugoWeb\IbexaBundle\Controller\QueryController:
    autowire: true
    autoconfigure: true

  MugoWeb\IbexaBundle\Controller\ToolsController:
    autowire: true
    autoconfigure: true

  MugoWeb\IbexaBundle\Controller\InspectController:
    autowire: true
    autoconfigure: true

  MugoWeb\IbexaBundle\Service\ContentManager:
    autowire: true
    autoconfigure: true

  # Field filter
  mugo_web.search.legacy.gateway.criterion_handler.common.field:
    class: MugoWeb\IbexaBundle\Search\Legacy\Content\Common\Gateway\CriterionHandler\Field
    parent: ezpublish.search.legacy.gateway.criterion_handler.base
    arguments:
      $connection: "@ibexa.api.storage_engine.legacy.connection"
      $contentTypeHandler: '@Ibexa\Contracts\Core\Persistence\Content\Type\Handler'
    tags:
      - { name: ibexa.search.legacy.gateway.criterion_handler.content }
      - { name: ibexa.search.legacy.gateway.criterion_handler.location }
